### ISSUE TITLE
new problem in Field.tovtk2 method

### ISSUE THREAD

**Issue by grauchs** [mupif/mupif#11]
I am running my test problem in the following distributed configuration:
- name server and control script on a windows PC, with python3.6
- two application servers on one linux machine
I get the following error message in field.tovtk2, which I don't get under linux, i.e. ns and control script on one linux machine, two application servers on another linux machine. Please note that issue #3 has also been fixed in the windoes pyvtk version. The error only happens when I retrieve the field using the getfield method. If I retrieve it using the getFieldURI method, this error does not occur, but issue #10 occurs. Here is the error output from the control script window:

Traceback (most recent call last):
  File "testrundist-v1.py", line 116, in <module>
    res1.toVTK2('testoutput-d',format='ascii')
  File "C:\Users\rauchs\AppData\Roaming\Python\Python36\site-packages\mupif\Fiel
d.py", line 722, in toVTK2
    self.field2VTKData().tofile(filename=fileName,format=format)
  File "C:\Users\rauchs\AppData\Roaming\Python\Python36\site-packages\mupif\Fiel
d.py", line 416, in field2VTKData
    return pyvtk.VtkData(self.mesh.getVTKRepresentation(), pyvtk.PointData(pyvtk
.Vectors(self.value,**vectorsKw),lookupTable), 'Unstructured Grid Example')
  File "C:\Users\rauchs\AppData\Roaming\Python\Python36\site-packages\mupif\Mesh
.py", line 678, in getVTKRepresentation
    return pyvtk.UnstructuredGrid(vertices, hexahedron=hexahedrons, tetra=tetrah
edrons, quad=quads, triangle=triangles)
  File "C:\Users\rauchs\AppData\Roaming\Python\Python36\site-packages\pyvtk\Unst
ructuredGrid.py", line 73, in __init__
    raise ValueError('In cell %s: must be (seq of seq|seq) integers less than %s
'%(k,sz))
ValueError: In cell quad: must be (seq of seq|seq) integers less than 60
Exception ignored in: <bound method RemoteApplication.__del__ of <mupif.Applicat
ion.RemoteApplication object at 0x06D6FB90>>
Traceback (most recent call last):
  File "C:\Users\rauchs\AppData\Roaming\Python\Python36\site-packages\mupif\Appl
ication.py", line 341, in __del__
  File "C:\Users\rauchs\AppData\Roaming\Python\Python36\site-packages\mupif\Appl
ication.py", line 323, in terminate
  File "C:\Users\rauchs\AppData\Roaming\Python\Python36\site-packages\Pyro4\core
.py", line 179, in __call__
  File "C:\Users\rauchs\AppData\Roaming\Python\Python36\site-packages\Pyro4\core
.py", line 442, in _pyroInvoke
  File "C:\Users\rauchs\AppData\Roaming\Python\Python36\site-packages\Pyro4\util
.py", line 162, in deserializeData
  File "C:\Users\rauchs\AppData\Roaming\Python\Python36\site-packages\Pyro4\util
.py", line 433, in loads
AttributeError: Can't get attribute 'AttributeError' on None
2018-04-06 15:17:55 INFO:Application.py:327 RemoteApplication: Terminating jobMa
nager job 1@Mupif.JobManager@Solver1 on <mupif.JobManager.RemoteJobManager objec
t at 0x06D6FA50>

**Comment by vit-smilauer** [comment]
This error ends with VTK, which complains about
ValueError: In cell quad: must be (seq of seq|seq) integers less than 60

The error could be initiated by Field.field2VTKData() which creates pyvtk.VtkData() instance with possibly wrong data. Could you please
1) check you have the same pyvtk versions on Linux/Windows machines
2) send me compressed field file created by Filed.dumpToLocalFile() to explore internal data structure
3) try using more advanced Field.toVTK3() creating vtu data files, similar to vtk data files. It uses vtk module instead of pyvtk module and may fix the problem.

**Comment by grauchs** [comment]
Here is some of the requested info:
1. pyvtk versions are the same on Linux and Windows.
2. here is the field to be output, dumped by dumpToLocalFile method. The zip archive conbtains 2 versions: one dumped under linux and one under windows
[dump.zip](https://github.com/mupif/mupif/files/1915409/dump.zip)
3. I cannot install the vtk module under windows using pip. It can install it under linux, but then I get an error during execution of manyToVTK3 method:
Traceback (most recent call last):
  File "testrundist-v1.py", line 122, in <module>
    res1.toVTK3('testoutput-d',**d)
  File "/usr/local/lib/python3.6/site-packages/mupif-2.0.0-py3.6.egg/mupif/Field.py", line 780, in toVTK3
    return self.manyToVTK3([self],fileName,**kw)
  File "/usr/local/lib/python3.6/site-packages/mupif-2.0.0-py3.6.egg/mupif/Field.py", line 809, in manyToVTK3
    for i in range(nn): arr.SetTuple(i,f._giveValue(i).getValue())
ValueError: expects 0 <= tupleIdx && tupleIdx < GetNumberOfTuples()
Exception ignored in: <bound method RemoteApplication.__del__ of <mupif.Application.RemoteApplication object at 0x7f9fa0233cf8>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/mupif-2.0.0-py3.6.egg/mupif/Application.py", line 341, in __del__
  File "/usr/local/lib/python3.6/site-packages/mupif-2.0.0-py3.6.egg/mupif/Application.py", line 323, in terminate
  File "/usr/local/lib/python3.6/site-packages/Pyro4/core.py", line 179, in __call__
  File "/usr/local/lib/python3.6/site-packages/Pyro4/core.py", line 442, in _pyroInvoke
  File "/usr/local/lib/python3.6/site-packages/Pyro4/util.py", line 162, in deserializeData
  File "/usr/local/lib/python3.6/site-packages/Pyro4/util.py", line 433, in loads
AttributeError: Can't get attribute 'AttributeError' on None

**Comment by grauchs** [comment]
Sorry, I hit the wrong button

**Comment by nitramkaroh** [comment]
There is a bug in pyvtk version 0.5.18 as described here https://github.com/pearu/pyvtk/pull/11 
The bug is fixed in this commit https://github.com/pearu/pyvtk/pull/11/commits/19564635507bdc6bee06cc295f0d60dfbba9c249 and should be available in the pip distribution. 
I tried it with the bug fix and it is working fine now.

**Comment by grauchs** [comment]
Updating the file DataSet.py with its version from the latest pyvtk commit has solved the issue!
