### ISSUE TITLE
problem in execution using VPN

### ISSUE THREAD

**Issue by grauchs** [mupif/mupif#12]
In the procided example666 running under VPN, I can reach the vpn nameserver and start the jobmanagers. Once the control script tries to register an application, it fails. The output of the control script is given below. Strange is the fact that manual setting up of ssh tunnels is asked for.

$$$ Starting distributed mupif execution
2018-05-31 11:17:30 DEBUG:PyroUtil.py:172 Can connect to a LISTENING port of nameserver on 172.30.0.1:9090

2018-05-31 11:17:30 DEBUG:PyroUtil.py:182 Connected to NameServer on 172.30.0.1:9090. Pyro4 version on your localhost is 4.54

$$$ nameserver connected
2018-05-31 11:17:30 INFO:PyroUtil.py:508 Located Job Manager Mupif.JobManager@Solver2 at: 172.30.0.161 44383 None None

L None 172.30.0.161 44383 rauchs 172.30.0.161
2018-05-31 11:17:30 INFO:PyroUtil.py:119 If ssh tunnel does not exist, do it manually using a command e.g. ssh -L None:172.30.0.161:44383 rauchs@172.30.0.161 -N  , or putty.exe -L None:172.30.0.161:44383 rauchs@172.30.0.161 -N

2018-05-31 11:17:31 DEBUG:PyroUtil.py:243 Application Mupif.JobManager@Solver2, found URI PYRO:obj_47ebdb879ab645eb9cef3240cc2c0ab6@172.30.0.161:44383 on ('172.30.0.161', 44383, 'None', 'None') from a nameServer <Pyro4.core.Proxy at 0x7fcf906e0710; connected; for PYRO:Pyro.NameServer@172.30.0.1:9090>

2018-05-31 11:17:31 INFO:PyroUtil.py:251 Connecting to application Mupif.JobManager@Solver2 with <Pyro4.core.Proxy at 0x7fcf906e0e48; not connected; for PYRO:obj_47ebdb879ab645eb9cef3240cc2c0ab6@172.30.0.161:44383>

2018-05-31 11:17:31 DEBUG:PyroUtil.py:253 Connected to Mupif.JobManager.SimpleJobManager2 with the application Mupif.JobManager@Solver2

$$$ jobmanager 2 found
2018-05-31 11:17:31 INFO:PyroUtil.py:508 Located Job Manager Mupif.JobManager@Solver1 at: 172.30.0.161 44382 None None

L None 172.30.0.161 44382 rauchs 172.30.0.161
2018-05-31 11:17:31 INFO:PyroUtil.py:119 If ssh tunnel does not exist, do it manually using a command e.g. ssh -L None:172.30.0.161:44382 rauchs@172.30.0.161 -N  , or putty.exe -L None:172.30.0.161:44382 rauchs@172.30.0.161 -N

2018-05-31 11:17:32 DEBUG:PyroUtil.py:243 Application Mupif.JobManager@Solver1, found URI PYRO:obj_423756b9c3d94f6d8115d005c906842c@172.30.0.161:44382 on ('172.30.0.161', 44382, 'None', 'None') from a nameServer <Pyro4.core.Proxy at 0x7fcf906e0710; connected; for PYRO:Pyro.NameServer@172.30.0.1:9090>

2018-05-31 11:17:32 INFO:PyroUtil.py:251 Connecting to application Mupif.JobManager@Solver1 with <Pyro4.core.Proxy at 0x7fcf906e0f60; not connected; for PYRO:obj_423756b9c3d94f6d8115d005c906842c@172.30.0.161:44382>

2018-05-31 11:17:32 DEBUG:PyroUtil.py:253 Connected to Mupif.JobManager.SimpleJobManager2 with the application Mupif.JobManager@Solver1

$$$ jobmanager 1 found
$$$ creating jobs
$$$ Creating  job 2
2018-05-31 11:17:32 DEBUG:PyroUtil.py:543 Trying to connect to JobManager

2018-05-31 11:17:33 INFO:PyroUtil.py:561 Allocated job, returned record from jobManagaer:(1, '1@Mupif.JobManager@Solver2', 9250)

L 6250 172.30.0.161 9250 rauchs 172.30.0.161
2018-05-31 11:17:33 INFO:PyroUtil.py:119 If ssh tunnel does not exist, do it manually using a command e.g. ssh -L 6250:172.30.0.161:9250 rauchs@172.30.0.161 -N  , or putty.exe -L 6250:172.30.0.161:9250 rauchs@172.30.0.161 -N

2018-05-31 11:17:34 DEBUG:PyroUtil.py:243 Application 1@Mupif.JobManager@Solver2, found URI PYRO:obj_0a6f556e488848878a0005383014944c@172.30.0.161:6250 on ('172.30.0.161', 9250, '172.30.0.161', '6250') from a nameServer <Pyro4.core.Proxy at 0x7fcf906e0710; connected; for PYRO:Pyro.NameServer@172.30.0.1:9090>

2018-05-31 11:17:34 INFO:PyroUtil.py:251 Connecting to application 1@Mupif.JobManager@Solver2 with <Pyro4.core.Proxy at 0x7fcf906fe550; not connected; for PYRO:obj_0a6f556e488848878a0005383014944c@172.30.0.161:6250>

2018-05-31 11:17:34 ERROR:PyroUtil.py:255 Communication error, perhaps a wrong key hkey=mupif-secret-key?

2018-05-31 11:17:34 ERROR:Example666.py:57 cannot connect: [Errno 111] Connection refused
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/Pyro4/core.py", line 487, in __pyroCreateConnection
    sock = socketutil.createSocket(connect=connect_location, reuseaddr=Pyro4.config.SOCK_REUSE, timeout=self.__pyroTimeout, nodelay=Pyro4.config.SOCK_NODELAY)
  File "/usr/local/lib/python3.6/site-packages/Pyro4/socketutil.py", line 295, in createSocket
    sock.connect(connect)
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Example666.py", line 44, in <module>
    app2 = PyroUtil.allocateApplicationWithJobManager( ns, JobMan2, cfg.jobNatPorts[0], cfg.hkey, PyroUtil.SSHContext(sshClient=cfg.sshClient, options=cfg.options, sshHost=cfg.sshHost) )
  File "/usr/local/lib/python3.6/site-packages/mupif-2.0.0-py3.6.egg/mupif/PyroUtil.py", line 580, in allocateApplicationWithJobManager
    app = _connectApp(ns, retRec[1], hkey)
  File "/usr/local/lib/python3.6/site-packages/mupif-2.0.0-py3.6.egg/mupif/PyroUtil.py", line 252, in _connectApp
    sig = app2.getApplicationSignature()
  File "/usr/local/lib/python3.6/site-packages/Pyro4/core.py", line 263, in __getattr__
    self._pyroGetMetadata()
  File "/usr/local/lib/python3.6/site-packages/Pyro4/core.py", line 570, in _pyroGetMetadata
    self.__pyroCreateConnection()
  File "/usr/local/lib/python3.6/site-packages/Pyro4/core.py", line 522, in __pyroCreateConnection
    raise ce
Pyro4.errors.CommunicationError: cannot connect: [Errno 111] Connection refused
Traceback (most recent call last):
  File "Example666.py", line 82, in <module>
    print(app2.getApplicationSignature())
AttributeError: 'NoneType' object has no attribute 'getApplicationSignature'

**Comment by nitramkaroh** [comment]
I think that this issue is due to line 43 self.jobNatPorts = list(range(6050, 6100))  in your Config.py
There should be self.jobNatPorts = [None] for the vpn mode, i.e. mode 2.

**Comment by grauchs** [comment]
I got it running under vpn on Friday, but starting this week, I get the following error message:
2018-06-13 16:08:33 ERROR:PyroUtil.py:174 Can not connect to a LISTENING port of nameserver on 172.30.0.1:9090. Does a firewall block INPUT or OUTPUT on the port? Exiting.
I had the same problem with the same error message for a few weeks using the ssh protocol, and I got it fixed now by our IT department, as it was an issue with the virus scanner blocking python execution. According to them, they don't see no other blocked ports in our firewall. Thus my question: could it be that there is a problem with the access to the mupif nameserver in Prague?

**Comment by grauchs** [comment]
Thr problem persists! In the link above, there are  three machines of LISTwith very recent pings of today, but for the nameserver, I see 
Nameserver IP: 172.30.0.1, Nameserver Port: 9090, Status: failed, note: connection refused. 

The full error message I get under linux reads:
2018-06-14 07:56:24 ERROR:PyroUtil.py:174 Can not connect to a LISTENING port of nameserver on 172.30.0.1:9090. Does a firewall block INPUT or OUTPUT on the port? Exiting.
Traceback (most recent call last):
  File "/home/rauchs/.local/lib/python3.6/site-packages/mupif-2.0.1-py3.6.egg/mupif/PyroUtil.py", line 166, in connectNameServer
    s.connect((nshost, nsport))
ConnectionRefusedError: [Errno 111] Connection refused

Under windows, the error message also states that the connection is actively refused by the target machine. So apparently, the connection is refused by the nameserver, if I understand correcly.

**Comment by nitramkaroh** [comment]
Sorry, that was our fault, we had to restart nameserver, it is working now.

**Comment by grauchs** [comment]
OK! I am able to run successfully two applications using to different application servers and another computer for running the control script under vpn using the vpn nameserver in Prague. The nice thing is that issue #10 does not occur, i.e. I can successfully run the script using either getField or getFieldURI.
