### ISSUE TITLE
issue with toVTK2 method of field class using vpn

### ISSUE THREAD

**Issue by grauchs** [mupif/mupif#13]
Here is the error message I get when running my control script on a windows PC addressing two linux servers. Th8is error doesn't happen when I am running the control script on a Linux machine. Please note that res1 is a field, created by getField. The error does not happen if the field is defined by getFieldURI.

$$$$ control file displacement field type <class 'mupif.Field.Field'>
Traceback (most recent call last):
  File "testrundist-v1.py", line 133, in <module>
    res1.toVTK2('testoutput-d',format='ascii')
  File "C:\Users\rauchs\AppData\Roaming\Python\Python36\site-packages\mupif-2.0.1-py3.6.egg\mupif\Field.py", line 721, in toVTK2
    self.field2VTKData().tofile(filename=fileName,format=format)
  File "C:\Users\rauchs\AppData\Roaming\Python\Python36\site-packages\mupif-2.0.1-py3.6.egg\mupif\Field.py", line 415, in field2VTKData
    return pyvtk.VtkData(self.mesh.getVTKRepresentation(), pyvtk.PointData(pyvtk.Vectors(self.value,**vectorsKw),lookupTable), 'Unstructured Grid Example')
  File "C:\Users\rauchs\AppData\Roaming\Python\Python36\site-packages\mupif-2.0.1-py3.6.egg\mupif\Mesh.py", line 677, in getVTKRepresentation
    return pyvtk.UnstructuredGrid(vertices, hexahedron=hexahedrons, tetra=tetrahedrons, quad=quads, triangle=triangles)
  File "C:\Users\rauchs\AppData\Roaming\Python\Python36\site-packages\pyvtk-0.5.18-py3.6.egg\pyvtk\UnstructuredGrid.py", line 73, in __init__
ValueError: In cell quad: must be (seq of seq|seq) integers less than 60
Exception ignored in: <bound method RemoteApplication.__del__ of <mupif.Application.RemoteApplication object at 0x07D8FCD0>>
Traceback (most recent call last):
  File "C:\Users\rauchs\AppData\Roaming\Python\Python36\site-packages\mupif-2.0.1-py3.6.egg\mupif\Application.py", line 349, in __del__
  File "C:\Users\rauchs\AppData\Roaming\Python\Python36\site-packages\mupif-2.0.1-py3.6.egg\mupif\Application.py", line 323, in terminate
  File "C:\Users\rauchs\AppData\Roaming\Python\Python36\site-packages\pyro4-4.54-py3.6.egg\Pyro4\core.py", line 179, in __call__
  File "C:\Users\rauchs\AppData\Roaming\Python\Python36\site-packages\pyro4-4.54-py3.6.egg\Pyro4\core.py", line 442, in _pyroInvoke
  File "C:\Users\rauchs\AppData\Roaming\Python\Python36\site-packages\pyro4-4.54-py3.6.egg\Pyro4\util.py", line 162, in deserializeData
  File "C:\Users\rauchs\AppData\Roaming\Python\Python36\site-packages\pyro4-4.54-py3.6.egg\Pyro4\util.py", line 433, in loads
AttributeError: Can't get attribute 'AttributeError' on None
2018-08-16 16:32:32 INFO:Application.py:328 RemoteApplication: Terminating jobManager job 1@Mupif.JobManager@Solver1 on Mupif.JobManager@Solver1

**Comment by grauchs** [comment]
The issue was the missing fix in pyvtk from issue #2 on the windows PC
