### ISSUE TITLE
error in makeFromVTK2

### ISSUE THREAD

**Issue by grauchs** [mupif/mupif#18]
when I am using makeFromVTK2, I get error, which I don't get when I am using makeFromVTK3. The messages on the screen are:
2020-01-20 11:19:07 DEBUG:UnstructuredGrid.py:125       getting 17773 points

2020-01-20 11:19:07 DEBUG:UnstructuredGrid.py:135       getting 258155 cell indexes

2020-01-20 11:19:09 DEBUG:UnstructuredGrid.py:148       getting 51631 cell types

2020-01-20 11:19:09 DEBUG:UnstructuredGrid.py:158 unstructured_grid_fromfile done

Traceback (most recent call last):
  File "meshinput.py", line 130, in <module>
    vtkfield=Field.Field.makeFromVTK2(vfile,'none')
  File "C:\Users\rauchs\AppData\Roaming\Python\Python37\site-packages\mupif\Field.py", line 782, in makeFromVTK2
    data = pyvtk.VtkData(fileName)  # this is where reading the file happens (inside pyvtk)
  File "C:\Users\rauchs\AppData\Roaming\Python\Python37\site-packages\pyvtk\__init__.py", line 138, in __init__
    self.fromfile(args[0])
  File "C:\Users\rauchs\AppData\Roaming\Python\Python37\site-packages\pyvtk\__init__.py", line 252, in fromfile
    lst.append(ff(f,n,sl[1:]))
  File "C:\Users\rauchs\AppData\Roaming\Python\Python37\site-packages\pyvtk\Vectors.py", line 41, in vectors_fromfile
    vectors += map(eval,common._getline(f).split(' '))
TypeError: a bytes-like object is required, not 'str'

**Comment by eudoxos** [comment]
Hi, I am closing old issues which (unfortunately) are stale and without response. I believe these issues are solved in newer versions of MuPIF. If I am mistaken, please feel free to re-open.

For this particular case, the issue is that `split` operating on `bytes` requires `bytes` as argument (so it should be `split(b' ')`. Python2 (which IIRC pyvtk was targeting) did not make the distinction between str and bytes, so it is probably pyvtk upstream issue.
