### ISSUE TITLE
method Field.toVTK2 not working for tensors?

### ISSUE THREAD

**Issue by grauchs** [mupif/mupif#2]
I manage to do field output for scalars and vectors. For tensors, I get the following error message:
File "/usr/local/.../mupif/Field.py", line 651, in toVTK2
  self.field2VTKData().tofile(fileName=fileName,format=format)
AttributeError: 'NoneType' object has no attribute 'tofile'
I noticed that in field2VTKData, there are branches for scalar and vector, but not for tensor. Is it possible that tensor output to VTH format is not implemented yet?
Or do I put the tensor in a wrong form?

**Comment by vit-smilauer** [comment]
Hi Grauchs,
I enhanced field2VTKData() and field2Image2D() for Tensors. The example is under Example10-stacTM-local/TensorFieldTest.py. I checked generated VTK files in paraview and it works. Note that tensors need 3x3 list in each vertex (cell), which is what expects pyvtk module at the end.

**Comment by grauchs** [comment]
When I run TensorFieldTest.py from Example 10, I get the following error message:
Traceback (most recent call last):
  File "TensorFieldTest.py", line 17, in <module>
    g.field2VTKData().tofile('Tensors')
  File "/usr/local/lib/python3.6/site-packages/pyvtk/__init__.py", line 203, in tofile
    f.write(self.to_string(format))
  File "/usr/local/lib/python3.6/site-packages/pyvtk/__init__.py", line 187, in to_string
    ret.append(self.point_data.to_string(format))
  File "/usr/local/lib/python3.6/site-packages/pyvtk/Data.py", line 46, in to_string
    ret += [a.to_string(format) for a in self.data]
  File "/usr/local/lib/python3.6/site-packages/pyvtk/Data.py", line 46, in <listcomp>
    ret += [a.to_string(format) for a in self.data]
  File "/usr/local/lib/python3.6/site-packages/pyvtk/Tensors.py", line 29, in to_string
    return '\n'.join(ret)
TypeError: sequence item 1: expected str instance, bytes found

I work under Linux Centos6, with python3.6, pyvtk0.5.18 and mupif 1.1.6.
Could the problem be related to this issue:
https://stackoverflow.com/questions/33054527/python-3-5-typeerror-a-bytes-like-object-is-required-not-str-when-writing-t

**Comment by vit-smilauer** [comment]
Dear Grauchs,
this problem is related to pyvtk module under Python3 and partially missing conversion from strings to bytes. Python2 works OK. I submitted this bug&fix to developers, however, you can fix it easily by modifying Tensors.py (mine is /usr/local/lib/python3.5/dist-packages/pyvtk/Tensors.py). Add bold text so it looks like:

  def to_string(self,format='ascii'):
        t = self.get_datatype(self.tensors)
        ret = [**(**'TENSORS %s %s'%(self.name,t)**).encode()**,
               self.seq_to_string(self.tensors,format,t)]
        return **b**'\n'.join(ret)

Regards. Vit.

**Comment by grauchs** [comment]
After switching from mupif 1 to the most recent version of mupif version 2, I got the following warnings and error messages when using Field.toVTK2 with tensors. Note that for scalars and vectors the field output with Field.2toVTK2 works flawlessly. There seems to be again an issue with the tensor format 3 x 3 values versus 1 * 9 values. For the error message, I have got no real clue! Could it be related to the unit I give to getField?

2017-12-11 09:47:51 WARNING:common.py:178 expected 3-sequence but got 9-<class 'tuple'>

2017-12-11 09:47:51 WARNING:common.py:178 expected 3-sequence but got 9-<class 'tuple'>

2017-12-11 09:47:51 WARNING:common.py:178 expected 3-sequence but got 9-<class 'tuple'>

Traceback (most recent call last):
  File "testrun-v4.py", line 66, in <module>
    res3.toVTK2('testoutput-s',format='ascii')
  File "/usr/local/lib/python3.6/site-packages/mupif-1.1.6-py3.6.egg/mupif/Field.py", line 703, in toVTK2
    self.field2VTKData().tofile(filename=fileName,format=format)
  File "/usr/local/lib/python3.6/site-packages/mupif-1.1.6-py3.6.egg/mupif/Field.py", line 406, in field2VTKData
    pyvtk.PointData(pyvtk.Tensors(self.value,**vectorsKw),lookupTable),'Unstructured Grid Example')
  File "/usr/local/lib/python3.6/site-packages/pyvtk/__init__.py", line 167, in __init__
    raise ValueError('DataSet (size=%s) and PointData (size=%s) have different sizes'%(s,s1))
ValueError: DataSet (size=60) and PointData (size=1) have different sizes

**Comment by vit-smilauer** [comment]
Hi,
tensors should be fixed now in dev-2.0 version. If you wait a few more days, dev-2.0 and master will be merged together and there will be master git version only. (The tensor problem emerged due to separate branches, merging would solve it later).

**Comment by grauchs** [comment]
I installed mupif-2.0.0. Now, all  problems which reappeared when I switched to mupif-dev-2.0 have disappeared, as you predicted.
