### ISSUE TITLE
Error running Example10

### ISSUE THREAD

**Issue by grauchs** [mupif/mupif#4]
While running Example10.py, I get the following error (which shows only up if matplotlib is installed):
Traceback (most recent call last):
  File "Example10.py", line 17, in <module>
    f.field2Image2D(title='Thermal', fileName='thermal.png')
  File "/usr/local/lib/python3.6/site-packages/mupif-1.1.6-py3.6.egg/mupif/Field.py", line 467, in field2Image2D
    vertexValue.append(value)
UnboundLocalError: local variable 'value' referenced before assignment

**Comment by vit-smilauer** [comment]
Hi,
this was already fixed in git version, now it is updated in Pypi as well.
