### ISSUE TITLE
Huge output when using evaluate at point outside of field mesh

### ISSUE THREAD

**Issue by grauchs** [mupif/mupif#5]
When I do setField using a mesh which is not conforming with the original field mesh, some points lie outside of the domain of the field mesh. The evaluate function then gives a huge output. There seem to be 2 issues with the output:
- therre seems to be a problem with logging: "TypeError: not all arguments converted during string formatting"
- one sort of message only gives 0 as information

Here is the output stemming from one single point outside of the mesh domain:
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 575, in format
    record.message = record.getMessage()
  File "/usr/local/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "testrun-v4.py", line 70, in <module>
    app2.setField(res1)
  File "/home/rauchs/ComPoSTe/Interface/composteAPI.py", line 269, in setField
    vec=field.evaluate(node.getCoordinates(),0.5)
  File "/usr/local/lib/python3.6/site-packages/mupif-1.1.7-py3.6.egg/mupif/Field.py", line 196, in evaluate
    return self._evaluate(positions, eps)
  File "/usr/local/lib/python3.6/site-packages/mupif-1.1.7-py3.6.egg/mupif/Field.py", line 231, in _evaluate
    log.error('Field::evaluate - no source cell found for position ', position)
Message: 'Field::evaluate - no source cell found for position '
Arguments: ((1000.0, 0.0, 0.0),)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 575, in format
    record.message = record.getMessage()
  File "/usr/local/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "testrun-v4.py", line 70, in <module>
    app2.setField(res1)
  File "/home/rauchs/ComPoSTe/Interface/composteAPI.py", line 269, in setField
    vec=field.evaluate(node.getCoordinates(),0.5)
  File "/usr/local/lib/python3.6/site-packages/mupif-1.1.7-py3.6.egg/mupif/Field.py", line 196, in evaluate
    return self._evaluate(positions, eps)
  File "/usr/local/lib/python3.6/site-packages/mupif-1.1.7-py3.6.egg/mupif/Field.py", line 231, in _evaluate
    log.error('Field::evaluate - no source cell found for position ', position)
Message: 'Field::evaluate - no source cell found for position '
Arguments: ((1000.0, 0.0, 0.0),)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 575, in format
    record.message = record.getMessage()
  File "/usr/local/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "testrun-v4.py", line 70, in <module>
    app2.setField(res1)
  File "/home/rauchs/ComPoSTe/Interface/composteAPI.py", line 269, in setField
    vec=field.evaluate(node.getCoordinates(),0.5)
  File "/usr/local/lib/python3.6/site-packages/mupif-1.1.7-py3.6.egg/mupif/Field.py", line 196, in evaluate
    return self._evaluate(positions, eps)
  File "/usr/local/lib/python3.6/site-packages/mupif-1.1.7-py3.6.egg/mupif/Field.py", line 233, in _evaluate
    log.debug(icell.number, icell.containsPoint(position), icell.glob2loc(position))
Message: 0
Arguments: (False, (False, (-18.00227703832303, 1.1019910889255309)))
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 575, in format
    record.message = record.getMessage()
  File "/usr/local/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "testrun-v4.py", line 70, in <module>
    app2.setField(res1)
  File "/home/rauchs/ComPoSTe/Interface/composteAPI.py", line 269, in setField
    vec=field.evaluate(node.getCoordinates(),0.5)
  File "/usr/local/lib/python3.6/site-packages/mupif-1.1.7-py3.6.egg/mupif/Field.py", line 196, in evaluate
    return self._evaluate(positions, eps)
  File "/usr/local/lib/python3.6/site-packages/mupif-1.1.7-py3.6.egg/mupif/Field.py", line 233, in _evaluate
    log.debug(icell.number, icell.containsPoint(position), icell.glob2loc(position))
Message: 0
Arguments: (False, (False, (-18.00227703832303, 1.1019910889255309)))

**Comment by vit-smilauer** [comment]
Fixed wrong formatting in log.debug(), log.error() and log. info()
