### ISSUE TITLE
problem when using evaluate method with tensors

### ISSUE THREAD

**Issue by grauchs** [mupif/mupif#6]
In the setField method, I use the evaluate method. For vectors, the output works, for tensors, I get the following error:
Traceback (most recent call last):
  File "testrun-v4.py", line 70, in <module>
    app2.setField(res3)
  File "/home/rauchs/ComPoSTe/Interface/composteAPI.py", line 269, in setField
    vec=field.evaluate(node.getCoordinates(),0.5)
  File "/usr/local/lib/python3.6/site-packages/mupif-1.1.7-py3.6.egg/mupif/Field.py", line 196, in evaluate
    return self._evaluate(positions, eps)
  File "/usr/local/lib/python3.6/site-packages/mupif-1.1.7-py3.6.egg/mupif/Field.py", line 219, in _evaluate
    answer = icell.interpolate(position, [self.values[i.getNumber()] for i in icell.getVertices()])
  File "/usr/local/lib/python3.6/site-packages/mupif-1.1.7-py3.6.egg/mupif/Cell.py", line 730, in interpolate
    0.25*(1.0+ac[0])*(1.0-ac[1])*vertexValues[3][i]) for i in range(len(vertexValues[0]))])
  File "/usr/local/lib/python3.6/site-packages/mupif-1.1.7-py3.6.egg/mupif/Cell.py", line 730, in <listcomp>
    0.25*(1.0+ac[0])*(1.0-ac[1])*vertexValues[3][i]) for i in range(len(vertexValues[0]))])
TypeError: 'numpy.float64' object cannot be interpreted as an integer

For information: the Tensor is given to the field constructor in getField as a tuple consisting in three tuples with each having three reals as members

**Comment by vit-smilauer** [comment]
Changed tensor representation back to a list with 9 positions. This should fix all of those problems.
